name: The Remix
favicon: null
layout_spectrum: 0.24566
typography_spectrum: 0.8222288
author:
  email: createtheremix@gmail.com
  url: www.theremix.com.au
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/43f3c184-7131-4e6c-9009-dc9928df7aec.jpg
navigation:
  - id: 1626755e-4341-49ad-b7ef-ac0cb64097e3
    url: 2016-07-17-what-is-the-remix.html
    name: WHAT IS THE REMIX
    type: content
  - id: b105ad4c-6d3c-4ced-8b2b-5745dc321943
    url: 2016-07-17-what-does-the-remix-program-entail.html
    name: WHAT DOES THE REMIX PROGRAM ENTAIL
    type: content
  - id: 4fdb78b7-15c2-4f9c-af02-b5b791d026a0
    url: 2016-07-17-remix-outcomes.html
    name: REMIX OUTCOMES
    type: content
  - id: 22679e3c-8ea1-46a7-aa13-f472d078cd98
    url: 2016-07-17-22679e3c-8ea1-46a7-aa13-f472d078cd98.html
    name: STATISTICS
    type: content
  - id: www.facebook.com/TheRemixEvent
    url: www.facebook.com/TheRemixEvent
    name: Connect with us on Facebook
    type: external
title: Create...Inspire...Contribute
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: Facebook
  appId: www.facebook.com/TheRemixEvent
color:
  brandColors:
    - '#7D7E7F'
    - '#000000'
    - '#EC008A'
    - '#00ADE6'
    - '#EFF1E6'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
