typography_spectrum: 0.8222288
color:
  saturation: 0.6130104
  lightness: 0.56963
  brandStrength: 0.5598164
  brandColors:
    - '#7D7E7F'
    - '#000000'
    - '#EC008A'
    - '#00ADE6'
    - '#EFF1E6'
  rhythmicContrast: 0.9313118
opengraph:
  type: Facebook
  appId: www.facebook.com/TheRemixEvent
layout_spectrum: 1
author:
  email: createtheremix@gmail.com
  url: www.theremix.com.au
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/43f3c184-7131-4e6c-9009-dc9928df7aec.jpg
name: The Remix
navigation: []
title: Create...Inspire...Contribute
