name: The Remix
favicon: null
layout_spectrum: 0.50193
typography_spectrum: 0.8222288
author:
  email: createtheremix@gmail.com
  url: www.theremix.com.au
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/43f3c184-7131-4e6c-9009-dc9928df7aec.jpg
navigation: []
title: Create...Inspire...Contribute
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: Facebook
  appId: www.facebook.com/TheRemixEvent
color:
  brandColors:
    - '#7D7E7F'
    - '#000000'
    - '#EC008A'
    - '#00ADE6'
    - '#EFF1E6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
